[project]
name = "funclib"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.2.0",
    "toolz>=1.0.0",
    "typing>=3.10.0.0",
]
